#!/usr/bin/env bash
echo "# === Hush — Generated production secrets ==="
echo "# Copy these values into .env.prod on the VPS."
echo "# Generated on $(date)"
echo ""
echo "POSTGRES_USER=hush"
echo "POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=\n' | head -c 32)"
echo "POSTGRES_DB=hush"
echo ""
echo "JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')"
echo "JWT_EXPIRES_IN=8h"
echo "COOKIE_SECRET=$(openssl rand -base64 48 | tr -d '\n')"
echo ""
echo "WEB_PORT=8080"
